version: '3.8'

services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: 'redis-server --loglevel warning'
    volumes:
      - cache:/data
  app:
    build: .
    depends_on:
      - cache
    environment:
      - "APP_KEY=${ZETTEL_APP_KEY}"
      - "APP_SECRET=${ZETTEL_APP_SECRET}"
    ports: 
      - 5000:5000
    command: './zettel-bot'

volumes:
  cache:
    driver: local
